# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-15 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('task_description', models.TextField()),
                ('task_status', models.CharField(choices=[('Inprogress', 'inprogress'), ('COMPLETED', 'completed'), ('PENDING', 'pending')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
